### ISSUE TITLE
Provide a poetry binary

### ISSUE THREAD

**Issue by alexeagle** [oxidase/rules_poetry#31]
examples/simple/README.md says

> The `poetry.lock` file can be updated with a locally installed `poetry` as `poetry update`.

But that assumes developers have poetry installed locally, and their versions might drift. I'd prefer to `bazel run @rules_poetry//poetry update` or something like that.

(note, I have this working here https://github.com/bazelbuild/rules_python/tree/poetry/examples/poetry but I'm not sure where the code belongs yet)

**Comment by oxidase** [comment]
Good catch! The doc line is outdated, I add `poetry_update` target to the example like

```
load("@rules_poetry//python:poetry.bzl", "poetry_update")

poetry_update(
    name = "update_lock",
    lock = "poetry.lock",
    toml = "pyproject.toml",
)
```
