### ISSUE TITLE
fix: add new default platform macos_14

### ISSUE THREAD

**Issue by oceanusxiv** [oxidase/rules_poetry#55]
The `_DEFAULT_PLATFORMS` dict in poetry_deps doesn't include the newest Mac release, `macosx_14_0_arm64`.

**Comment by oxidase** [comment]
@oceanusxiv please could you check if ⬆️  PR fixes issues with 94e11402e360f9696e94ea1e1fb793a262b31007 commit as 

```
git_override(
    module_name = "rules_poetry",
    commit = "94e11402e360f9696e94ea1e1fb793a262b31007"
    remote = "https://github.com/oxidase/rules_poetry.git",
)
```

If it is ok, I'll create a new release with fixes

**Comment by oceanusxiv** [comment]
Yeah this looks good, though I wonder if there's a more scalable way to do this....

**Comment by oxidase** [comment]
Thanks, will merge it now!

>  if there's a more scalable way to do this....

I don't see an automatic way to update the list which depends on `sysconfig.get_platform()` results for target platforms without a possibility to run target Python toolchains on the execution platform. 

`_DEFAULT_PLATFORMS` association converts a toolchain name to all _possible_  target platforms, which can be inconsistent for non-rules_python toolchains. For such cases [platforms](https://github.com/oxidase/rules_poetry/blob/27328444/python/extensions.bzl#L22) attribute allows to set associations for specific platforms not listed in the default association.
